export const CLEAR_APP_DATA = 'CLEAR_APP_DATA'
export const SET_METADATA = 'SET_METADATA'
export const SET_UID = 'SET_UID'
export const SIGN_IN_ANONYMOUS_FAILED = 'SIGN_IN_ANONYMOUS_FAILED'
export const SET_APP_LOADED = 'SET_APP_LOADED'
export const NOTIFY_STALE_APP_RESET = 'NOTIFY_STALE_APP_RESET'
export const GENERIC_ERROR = 'GENERIC_ERROR'
export const CLEAR_TOAST = 'CLEAR_TOAST'

// CAMERA PERMISSION ACTIONS
export const SET_CAMERA_ACCESS_STATUS = 'SET_CAMERA_ACCESS_STATUS'
export const CAMERA_ACCESS_ERROR = 'CAMERA_ACCESS_ERROR'

// RESTAURANT ACTIONS
export const FETCHING_RESTAURANT = 'FETCHING_RESTAURANT'
export const SET_RESTAURANT = 'SET_RESTAURANT'
export const SET_GLOBAL_TAGS = 'SET_TAGS'

// MENU ACTIONS
export const SET_MENU_ITEM_SELECTION = 'SET_MENU_ITEM_SELECTION'
export const REMOVE_MENU_ITEM_SELECTION = 'REMOVE_MENU_ITEM_SELECTION'
export const SET_MENU_ITEM = 'SET_MENU_ITEM'
export const SET_LISTENING_FOR_MENU_ITEMS = 'SET_LISTENING_FOR_MENU_ITEMS'

// CART ACTIONS
export const ADD_TO_CART = 'ADD_TO_CART'
export const ADD_TO_CART_ERROR = 'ADD_TO_CART_ERROR'
export const SET_CURRENT_CART_ITEM = 'SET_CURRENT_CART_ITEM'
export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM'
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'
export const SET_IS_SENDING_CART_ITEMS = 'SET_IS_SENDING_CART_ITEMS'
export const CLEAR_CART = 'CLEAR_CART'

// ORDER ACTIONS
export const SET_OID = 'SET_OID'
export const SET_LISTENING_FOR_BUCKETS = 'SET_LISTENING_FOR_BUCKETS'
export const SET_BUCKETS_SYNC_IN_PROGRESS = 'SET_BUCKETS_SYNC_IN_PROGRESS'
export const ADD_BUCKET = 'ADD_BUCKET'
export const NOTIFY_BUCKET = 'NOTIFY_BUCKET'
export const UPDATE_BUCKET = 'UPDATE_BUCKET'
export const ORDER_ERROR = 'ORDER_ERROR'
export const SET_IS_CLOSING_ORDER = 'SET_IS_CLOSING_ORDER'
export const CLOSE_ORDER = 'CLOSE_ORDER'
export const ORDER_CLOSED_BY_TENANT = 'ORDER_CLOSED_BY_TENANT'

// FEEDBACK ACTIONS
export const EMAIL_LINKED = 'EMAIL_LINKED'
export const EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE'
export const EMAIL_LINKING_FAILED = 'EMAIL_LINKING_FAILED'
export const SET_IS_SUBMITTING_FEEDBACK = 'SET_IS_SUBMITTING_FEEDBACK'
export const FEEDBACK_SUBMITTED = 'FEEDBACK_SUBMITTED'

// HOTEL ACTIONS
export const FETCHING_HOTEL = 'FETCHING_HOTEL'
export const SET_HOTEL = 'SET_HOTEL'
